var jsonCityString;$(document).ready(function(){$.ajax({type:"POST",url:"/istrat/ecom/api/axpx.aspx/getCityList",data:'',contentType:"application/json; charset=utf-8",dataType:"json",success:function(data,status){jsonCityString=$.parseJSON(data.d);cityCheckCook();fillTopCity();},failure:function(data,status){alert(data.d);}});});function cityCheckCook(){$(document).ready(function(){var city=$.cookie('selectedCity');$.ajax({type:"POST",url:"/istrat/ecom/api/axpx.aspx/cityChangeCheck",data:'{city : "'+$.cookie('selectedCity')+'"}',contentType:"application/json; charset=utf-8",dataType:"json",success:function(data,status){},failure:function(data,status){}});});}
function fillTopCity(){var cURL=$(location).attr('href');var clickatest;if(cURL.toLowerCase().indexOf('book-a-test'.toLowerCase())===-1){clickatest=false;}
else{clickatest=true;}
$(document).ready(function(){$('#mainCity li').remove();for(var i=0;i<jsonCityString.length;i++){var htmlCity='';var targetElemCity=$('#mainCity');if(!clickatest){if(jsonCityString[i].IsNew==1){htmlCity='<li><a href="" onclick="createCookie(\''+jsonCityString[i].Value+'\');"><img src="https://d2qhgd0topi90o.cloudfront.net/website/images/new-img.gif"  class="newGif" />'+jsonCityString[i].Text+'</a></li>';}
else{htmlCity='<li><a href="" onclick="createCookie(\''+jsonCityString[i].Value+'\');">'+jsonCityString[i].Text+'</a></li>';}}
else{if(cURL.toLowerCase().indexOf('book-a-test/cart'.toLowerCase())===-1){if(jsonCityString[i].IsNew==1){htmlCity='<li><a href="../book-a-test/'+jsonCityString[i].Value+'" onclick="createCookie(\''+jsonCityString[i].Value+'\');"><img src="https://d2qhgd0topi90o.cloudfront.net/website/images/new-img.gif"  class="newGif" />'+jsonCityString[i].Text+'</a></li>';}else{htmlCity='<li><a href="../book-a-test/'+jsonCityString[i].Value+'" onclick="createCookie(\''+jsonCityString[i].Value+'\');">'+jsonCityString[i].Text+'</a></li>';}}
else { if (jsonCityString[i].IsNew == 1) { htmlCity = '<li><a href="" onclick="createCookie(\'' + jsonCityString[i].Value +'\');"><img src="https://d2qhgd0topi90o.cloudfront.net/website/images/new-img.gif"  class="newGif" />'+jsonCityString[i].Text+'</a></li>';}else{htmlCity='<li><a href="" onclick="createCookie(\''+jsonCityString[i].Value+'\');">'+jsonCityString[i].Text+'</a></li>';}}}
targetElemCity.append(htmlCity);}
setNavigationColor();});}
function setNavigationColor(){var selText=$('#cityNameH').text();$("#mainCity a").each(function(){var href=$(this).text();if((href.toLowerCase().indexOf(selText.toLowerCase())!=-1)){$(this).closest('li a').addClass('active');}});}